Scrapper file
Drivello/Python-Web-Scrapper pull request #2
Opened 2023-04-25 12:54 UTC by Drivello

a scrapper file that allows the user to get all episodes from The Simpsons

2023-04-25 18:13 UTC, Pastorsin requested changes
Muy bien Nico!! Te deje unos comentarios :)

Acá te dejo comentarios generales, para seguirlo en próximas PRs (te recomiendo crear una branch por cada feature luego de mergear esto en master):
1. Nueva rama `logs`: Actualmente no se está logeando el proceso, estaría bueno incorporar logs que permita identificar en qué status está el script en todo momento. Utilizar: https://docs.python.org/3/library/logging.html
2. Nueva rama `tests`: Incorporar unit-tests:
    - Realizar un testing de unidad que mockee el HTML obtenido y verifique que los episodios fueron guardados correctamente. Podes usar el HTML que te devuelve la request y luego lo modificas para que sean 2 temporadas con 1 capítulo cada una.
    - Utilizar [pytest](https://docs.pytest.org/en/7.3.x/) o [unittest](https://docs.python.org/3/library/unittest.html).
3. Nueva rama `venv`: Incorporar virtualenv:
- Agregar un requirements.txt con las dependencias externas y utilizar un entorno virtual para instalarlas: https://realpython.com/python-virtual-environments-a-primer/
- Agregar un .gitignore de Python: https://github.com/github/gitignore/blob/main/Python.gitignore
- Aplicar un formateador, puede ser black: https://black.readthedocs.io/en/stable/

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +    asyncio.run(main())
Por qué optaste por `asyncio`? (No está mal, solo es para saber :))

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +        async with session.get('https://simpsonizados.me/serie/los-simpson/') as response:
Podes extraer la URL en una constante ?

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +                if response.status != 200:
Podes utilizar el método `response.ok` para no hardcodear el 200

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +                main_web_content = BeautifulSoup(await response.text(), 'lxml')
Esto se está utilizando en 2 partes, podes hacer una función: get_soup() para reutilizarlo en la función `get_season_data`

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +                episodes = []
Llamar `scraped_episodes` ?

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +    season_number = season.find(class_='title').text.split(' ')[1]
Podes castearlo a int?

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +        episode_number = chapter.find(class_='numerando').text.split(' - ')[1]
Podes castearlo a int?

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +    chapters = season.find_all('li')
Qué diferencia hay entre `chapters` y `episodes`?

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +    chapters = season.find_all('li')
Quizás podes renombrar esta variable a `season_episodes` para mantener la consistencia con la nomenclatura anterior, qué pensas?

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +            'season': f'Season {season_number}',
Guardar solo el número, se puede inferir que es una `season` por el nombre de la key

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +            'episode': episode,
Guardar solo el número, se puede saber el ID mediante (episode_dict[season], episode_dict[episode])

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +        episode_dict = {
Podes renombrar a `scraped_episode_detail`, evitar utilizar el tipo de dato para nombre de variables

2023-04-25 18:13 UTC, Pastorsin commented on scraping.py
> +                with open('simpsons_episodes.json', 'w') as file_open:
Podes hacer una función aparte para guardar el archivo y leerlo?

2023-04-25 18:16 UTC, Pastorsin commented on scraping.py
> +        async with session.get(url) as response:
Considerar respuestas con código < 200

2023-04-25 18:34 UTC, Drivello commented on scraping.py
> +    asyncio.run(main())
Es lo primero que aparecio en google cuando busque algo similar a Promise.All

2023-04-25 18:39 UTC, Drivello commented on scraping.py
> +        async with session.get('https://simpsonizados.me/serie/los-simpson/') as response:
Si, ahora lo agrego a un .env

2023-04-25 18:39 UTC, Drivello commented on scraping.py
> +                if response.status != 200:
Desconocia el dato, ahora lo tomo. Gracias

2023-04-25 19:11 UTC, Drivello commented on scraping.py
> +                main_web_content = BeautifulSoup(await response.text(), 'lxml')
Entendido. Gracias.

2023-04-25 19:12 UTC, Drivello commented on scraping.py
> +                episodes = []
Si, no me di cuenta que se podía confundir con la otra variable. Gracias por la observación.

2023-04-25 19:29 UTC, Drivello commented on scraping.py
> +    chapters = season.find_all('li')
Es verdad, se malentiende. Además, chapters es para obras literarias en todo caso. Gracias.

2023-04-25 19:30 UTC, Drivello commented on scraping.py
> +            'season': f'Season {season_number}',
Es verdad. Además, si lo pienso como backend, está mal devolverlo de esa manera.

2023-04-25 19:52 UTC, Drivello commented on scraping.py
> +                with open('simpsons_episodes.json', 'w') as file_open:
Es posible. Seguramente lo agregue después de un refactor.

2023-04-26 12:29 UTC, Pastorsin commented on scraping.py
> +SIMPSONS_URL = os.getenv('SIMPSONS_URL')
Está bien este approach, pero tené en cuenta que `getenv` retorna `None` si la env no existe. Podes utilizar `os.environ["SIMPSONS_URL"]` para que se lance la excepción `KeyError` en caso que no se especifique.

2023-04-26 13:07 UTC, merged